authKey : 7adc3b76eda219b8539402f267649acd

server:
  port: 8998
  

spring:
  application:
    name: zuul-gateway
    
feign:
  hystrix:
    enabled: true 
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    instance-id: zuul-gateway
    prefer-ip-address: true
    
zuul:
  sensitiveHeaders:  #去掉zuul的敏感头部，这样cookie才能读取写入
  ignored-services: "*"
  routes:
    api:
      path: /api/**
      service-id: api-service
