authKey : 7adc3b76eda219b8539402f267649acd

server:
  port: 8998
  

spring:
  application:
    name: zuul-gateway
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    instance-id: zuul-gateway
    prefer-ip-address: true
    

  
    