server:
  port: 8999
  

spring:
  application:
    name: api-service
  mvc:
    throw-exception-if-no-handler-found: true
    
  
eureka: 
  client: 
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    instance-id: api-service
    prefer-ip-address: true
    